/** Generated by tests/workflow-capture.spec.ts from actual QuickModeWorkspace UI.
 * Media, transcript, and completed outputs are synthetic capture-fixture data.
 * Coordinates are measured after final scroll in the 1280 × 900 screenshot.
 */
export interface WorkflowCapture {
  src: string;
  width: 1280;
  height: 900;
  focus: { x: number; y: number };
  target: { x: number; y: number; width: number; height: number };
  label: string;
}

export const WORKFLOW_CAPTURES: readonly WorkflowCapture[] = [
  {
    "src": "/workflow/import.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 640,
      "y": 411
    },
    "target": {
      "x": 128,
      "y": 266,
      "width": 1024,
      "height": 290
    },
    "label": "Import your video"
  },
  {
    "src": "/workflow/transcript.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 640,
      "y": 418.25
    },
    "target": {
      "x": 841.05,
      "y": 532.5,
      "width": 162.98,
      "height": 38
    },
    "label": "Get the transcript"
  },
  {
    "src": "/workflow/prompt.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 640,
      "y": 280.75
    },
    "target": {
      "x": 164,
      "y": 244.5,
      "width": 952,
      "height": 58
    },
    "label": "Describe your clips"
  },
  {
    "src": "/workflow/llm.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 640,
      "y": 504.5
    },
    "target": {
      "x": 164,
      "y": 525.5,
      "width": 952,
      "height": 82
    },
    "label": "Use your favorite LLM"
  },
  {
    "src": "/workflow/brand.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 820,
      "y": 453
    },
    "target": {
      "x": 505,
      "y": 313,
      "width": 161.92,
      "height": 34
    },
    "label": "Add music & your logo"
  },
  {
    "src": "/workflow/render.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 629.5,
      "y": 393.5
    },
    "target": {
      "x": 832,
      "y": 342,
      "width": 278,
      "height": 40
    },
    "label": "Choose a template & render"
  },
  {
    "src": "/workflow/download.png",
    "width": 1280,
    "height": 900,
    "focus": {
      "x": 441.2,
      "y": 495.26
    },
    "target": {
      "x": 980.14,
      "y": 254,
      "width": 150.86,
      "height": 30
    },
    "label": "Download your videos"
  }
];
